[package]
name = "native_app"
version = "0.1.0"
authors = ["Douady Pâris <paris.douady@hotmail.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

futures       = { version = "0.3.4", default-features = false, features = ["executor"] }
bytemuck      = "1.2.0"
egregoria     = { path = "../egregoria" }
geom          = { path = "../geom" }
wgpu_engine   = { path = "../wgpu_engine" }
common        = { path = "../common" }
mint          = "0.5.6"
imgui-inspect = { path = "../imgui-inspect" }
imgui-inspect-derive = { path = "../imgui-inspect-derive" }
imgui-wgpu    = {git = "https://github.com/francesco-cattoglio/imgui-wgpu-rs", branch="tracking_wgpu_75e77d1"}
imgui-winit-support = "0.7.0"
map_model     = { path = "../map_model" }
flat_spatial  = { path = "../flat_spatial" }
log-panics    = { version = "2.0.0", features=["with-backtrace"] }
log           = "0.4.11"
inline_tweak  = "1.0.6"
imgui         = "0.7"
legion        = { version = "0.4.0", default-features = false, features = ["codegen", "serialize"] }
ordered-float = "2.0.0"
serde         = "1.0"
rodio         = { version = "0.13.0", default-features = false, features = ["vorbis"] }
slotmap       = { version = "1.0.2", default-features = false }
winit         = "0.24"
inventory     = "0.1.10"
paste         = "1.0.4"